name: Fetch PagerDuty iCal and Update Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can use the latest version you prefer

      - name: Install dependencies
        run: |
          npm install  # This will install all dependencies listed in package.json, including node-fetch

      - name: Set up GitHub token for push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Set up SSH key for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fetch iCal Data
        run: |
          node scripts/fetch-ical.js  # Or another method you use to generate the JSON

      - name: Pull latest changes from remote
        run: |
          git pull origin main

      - name: Commit and push changes
        run: |
          git add oncall.json
          git commit -m "Update oncall.json [skip ci]"
          git push git@github.com:Roadhogs/PDCal.git HEAD:main  # Use SSH URL for push
