name: Fetch PagerDuty iCal and convert to JSON

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch ical.js

      - name: Run fetch script
        run: node scripts/fetch-ical.js
        env:
          ICAL_URL: ${{ secrets.PD_ICAL_URL }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add oncall.json
          git commit -m "Update oncall.json [skip ci]" || echo "No changes"
          git push
