name: Fetch iCal and Process

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest  # Specifies the virtual environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Debug current working directory
      run: pwd  # This will help you see the current directory

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Installs dependencies from package.json

    - name: Run fetch-ical.mjs
      run: node scripts/fetch-ical.mjs  # Run the script (adjust the path if necessary)
